// ─────────────────────────────────────────────────────────────────────────────
// fourFrames — the FOUR celebration as a transparent PNG sequence.
//
// Cut from "ball animation/ball_four.mp4" (1280x720, 24fps, same
// framing as the wicket clip) by scripts/build_wicket_frames.py's pipeline:
// distance matte from the near-black background + solid-ball hole fill.
// 88 frames, starting and ending on the idle ball so the swap with the
// static spectator ball is seamless. Geometry measured on the hand-off frame.
// ─────────────────────────────────────────────────────────────────────────────
export const FOUR_FRAMES = [
  require('../../../assets/ball/four_frames/f00.png'),
  require('../../../assets/ball/four_frames/f01.png'),
  require('../../../assets/ball/four_frames/f02.png'),
  require('../../../assets/ball/four_frames/f03.png'),
  require('../../../assets/ball/four_frames/f04.png'),
  require('../../../assets/ball/four_frames/f05.png'),
  require('../../../assets/ball/four_frames/f06.png'),
  require('../../../assets/ball/four_frames/f07.png'),
  require('../../../assets/ball/four_frames/f08.png'),
  require('../../../assets/ball/four_frames/f09.png'),
  require('../../../assets/ball/four_frames/f10.png'),
  require('../../../assets/ball/four_frames/f11.png'),
  require('../../../assets/ball/four_frames/f12.png'),
  require('../../../assets/ball/four_frames/f13.png'),
  require('../../../assets/ball/four_frames/f14.png'),
  require('../../../assets/ball/four_frames/f15.png'),
  require('../../../assets/ball/four_frames/f16.png'),
  require('../../../assets/ball/four_frames/f17.png'),
  require('../../../assets/ball/four_frames/f18.png'),
  require('../../../assets/ball/four_frames/f19.png'),
  require('../../../assets/ball/four_frames/f20.png'),
  require('../../../assets/ball/four_frames/f21.png'),
  require('../../../assets/ball/four_frames/f22.png'),
  require('../../../assets/ball/four_frames/f23.png'),
  require('../../../assets/ball/four_frames/f24.png'),
  require('../../../assets/ball/four_frames/f25.png'),
  require('../../../assets/ball/four_frames/f26.png'),
  require('../../../assets/ball/four_frames/f27.png'),
  require('../../../assets/ball/four_frames/f28.png'),
  require('../../../assets/ball/four_frames/f29.png'),
  require('../../../assets/ball/four_frames/f30.png'),
  require('../../../assets/ball/four_frames/f31.png'),
  require('../../../assets/ball/four_frames/f32.png'),
  require('../../../assets/ball/four_frames/f33.png'),
  require('../../../assets/ball/four_frames/f34.png'),
  require('../../../assets/ball/four_frames/f35.png'),
  require('../../../assets/ball/four_frames/f36.png'),
  require('../../../assets/ball/four_frames/f37.png'),
  require('../../../assets/ball/four_frames/f38.png'),
  require('../../../assets/ball/four_frames/f39.png'),
  require('../../../assets/ball/four_frames/f40.png'),
  require('../../../assets/ball/four_frames/f41.png'),
  require('../../../assets/ball/four_frames/f42.png'),
  require('../../../assets/ball/four_frames/f43.png'),
  require('../../../assets/ball/four_frames/f44.png'),
  require('../../../assets/ball/four_frames/f45.png'),
  require('../../../assets/ball/four_frames/f46.png'),
  require('../../../assets/ball/four_frames/f47.png'),
  require('../../../assets/ball/four_frames/f48.png'),
  require('../../../assets/ball/four_frames/f49.png'),
  require('../../../assets/ball/four_frames/f50.png'),
  require('../../../assets/ball/four_frames/f51.png'),
  require('../../../assets/ball/four_frames/f52.png'),
  require('../../../assets/ball/four_frames/f53.png'),
  require('../../../assets/ball/four_frames/f54.png'),
  require('../../../assets/ball/four_frames/f55.png'),
  require('../../../assets/ball/four_frames/f56.png'),
  require('../../../assets/ball/four_frames/f57.png'),
  require('../../../assets/ball/four_frames/f58.png'),
  require('../../../assets/ball/four_frames/f59.png'),
  require('../../../assets/ball/four_frames/f60.png'),
  require('../../../assets/ball/four_frames/f61.png'),
  require('../../../assets/ball/four_frames/f62.png'),
  require('../../../assets/ball/four_frames/f63.png'),
  require('../../../assets/ball/four_frames/f64.png'),
  require('../../../assets/ball/four_frames/f65.png'),
  require('../../../assets/ball/four_frames/f66.png'),
  require('../../../assets/ball/four_frames/f67.png'),
  require('../../../assets/ball/four_frames/f68.png'),
  require('../../../assets/ball/four_frames/f69.png'),
  require('../../../assets/ball/four_frames/f70.png'),
  require('../../../assets/ball/four_frames/f71.png'),
  require('../../../assets/ball/four_frames/f72.png'),
  require('../../../assets/ball/four_frames/f73.png'),
  require('../../../assets/ball/four_frames/f74.png'),
  require('../../../assets/ball/four_frames/f75.png'),
  require('../../../assets/ball/four_frames/f76.png'),
  require('../../../assets/ball/four_frames/f77.png'),
  require('../../../assets/ball/four_frames/f78.png'),
  require('../../../assets/ball/four_frames/f79.png'),
  require('../../../assets/ball/four_frames/f80.png'),
  require('../../../assets/ball/four_frames/f81.png'),
  require('../../../assets/ball/four_frames/f82.png'),
  require('../../../assets/ball/four_frames/f83.png'),
  require('../../../assets/ball/four_frames/f84.png'),
  require('../../../assets/ball/four_frames/f85.png'),
  require('../../../assets/ball/four_frames/f86.png'),
  require('../../../assets/ball/four_frames/f87.png'),
];

export const FOUR_FPS = 12;
// canvas edge / ball diameter, and ball-centre fraction down the canvas
export const FOUR_CANVAS_PER_BALL = 200 / 95;
export const FOUR_BALL_CENTER_FRAC_Y = 0.55;
