// ─────────────────────────────────────────────────────────────────────────────
// sixFrames — the SIX celebration as a transparent PNG sequence.
//
// Cut from "ball animation/ball_six.mp4" (1280x720, 24fps, same
// framing as the wicket clip) by scripts/build_wicket_frames.py's pipeline:
// distance matte from the near-black background + solid-ball hole fill.
// 83 frames, starting and ending on the idle ball so the swap with the
// static spectator ball is seamless. Geometry measured on the hand-off frame.
// ─────────────────────────────────────────────────────────────────────────────
export const SIX_FRAMES = [
  require('../../../assets/ball/six_frames/s00.png'),
  require('../../../assets/ball/six_frames/s01.png'),
  require('../../../assets/ball/six_frames/s02.png'),
  require('../../../assets/ball/six_frames/s03.png'),
  require('../../../assets/ball/six_frames/s04.png'),
  require('../../../assets/ball/six_frames/s05.png'),
  require('../../../assets/ball/six_frames/s06.png'),
  require('../../../assets/ball/six_frames/s07.png'),
  require('../../../assets/ball/six_frames/s08.png'),
  require('../../../assets/ball/six_frames/s09.png'),
  require('../../../assets/ball/six_frames/s10.png'),
  require('../../../assets/ball/six_frames/s11.png'),
  require('../../../assets/ball/six_frames/s12.png'),
  require('../../../assets/ball/six_frames/s13.png'),
  require('../../../assets/ball/six_frames/s14.png'),
  require('../../../assets/ball/six_frames/s15.png'),
  require('../../../assets/ball/six_frames/s16.png'),
  require('../../../assets/ball/six_frames/s17.png'),
  require('../../../assets/ball/six_frames/s18.png'),
  require('../../../assets/ball/six_frames/s19.png'),
  require('../../../assets/ball/six_frames/s20.png'),
  require('../../../assets/ball/six_frames/s21.png'),
  require('../../../assets/ball/six_frames/s22.png'),
  require('../../../assets/ball/six_frames/s23.png'),
  require('../../../assets/ball/six_frames/s24.png'),
  require('../../../assets/ball/six_frames/s25.png'),
  require('../../../assets/ball/six_frames/s26.png'),
  require('../../../assets/ball/six_frames/s27.png'),
  require('../../../assets/ball/six_frames/s28.png'),
  require('../../../assets/ball/six_frames/s29.png'),
  require('../../../assets/ball/six_frames/s30.png'),
  require('../../../assets/ball/six_frames/s31.png'),
  require('../../../assets/ball/six_frames/s32.png'),
  require('../../../assets/ball/six_frames/s33.png'),
  require('../../../assets/ball/six_frames/s34.png'),
  require('../../../assets/ball/six_frames/s35.png'),
  require('../../../assets/ball/six_frames/s36.png'),
  require('../../../assets/ball/six_frames/s37.png'),
  require('../../../assets/ball/six_frames/s38.png'),
  require('../../../assets/ball/six_frames/s39.png'),
  require('../../../assets/ball/six_frames/s40.png'),
  require('../../../assets/ball/six_frames/s41.png'),
  require('../../../assets/ball/six_frames/s42.png'),
  require('../../../assets/ball/six_frames/s43.png'),
  require('../../../assets/ball/six_frames/s44.png'),
  require('../../../assets/ball/six_frames/s45.png'),
  require('../../../assets/ball/six_frames/s46.png'),
  require('../../../assets/ball/six_frames/s47.png'),
  require('../../../assets/ball/six_frames/s48.png'),
  require('../../../assets/ball/six_frames/s49.png'),
  require('../../../assets/ball/six_frames/s50.png'),
  require('../../../assets/ball/six_frames/s51.png'),
  require('../../../assets/ball/six_frames/s52.png'),
  require('../../../assets/ball/six_frames/s53.png'),
  require('../../../assets/ball/six_frames/s54.png'),
  require('../../../assets/ball/six_frames/s55.png'),
  require('../../../assets/ball/six_frames/s56.png'),
  require('../../../assets/ball/six_frames/s57.png'),
  require('../../../assets/ball/six_frames/s58.png'),
  require('../../../assets/ball/six_frames/s59.png'),
  require('../../../assets/ball/six_frames/s60.png'),
  require('../../../assets/ball/six_frames/s61.png'),
  require('../../../assets/ball/six_frames/s62.png'),
  require('../../../assets/ball/six_frames/s63.png'),
  require('../../../assets/ball/six_frames/s64.png'),
  require('../../../assets/ball/six_frames/s65.png'),
  require('../../../assets/ball/six_frames/s66.png'),
  require('../../../assets/ball/six_frames/s67.png'),
  require('../../../assets/ball/six_frames/s68.png'),
  require('../../../assets/ball/six_frames/s69.png'),
  require('../../../assets/ball/six_frames/s70.png'),
  require('../../../assets/ball/six_frames/s71.png'),
  require('../../../assets/ball/six_frames/s72.png'),
  require('../../../assets/ball/six_frames/s73.png'),
  require('../../../assets/ball/six_frames/s74.png'),
  require('../../../assets/ball/six_frames/s75.png'),
  require('../../../assets/ball/six_frames/s76.png'),
  require('../../../assets/ball/six_frames/s77.png'),
  require('../../../assets/ball/six_frames/s78.png'),
  require('../../../assets/ball/six_frames/s79.png'),
  require('../../../assets/ball/six_frames/s80.png'),
  require('../../../assets/ball/six_frames/s81.png'),
  require('../../../assets/ball/six_frames/s82.png'),
];

export const SIX_FPS = 12;
// canvas edge / ball diameter, and ball-centre fraction down the canvas
export const SIX_CANVAS_PER_BALL = 200 / 84;
export const SIX_BALL_CENTER_FRAC_Y = 0.565;
